name: Get A Commit Test

on:
  push:
    branches: [ "main" ]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 履歴を全部取得（重要）


      - name: Get previous commit from event payload
        run: |
          BEFORE_SHA=$(jq -r .before $GITHUB_EVENT_PATH)
          echo "Previous commit: $BEFORE_SHA"
          echo "BEFORE_SHA=$BEFORE_SHA" >> $GITHUB_ENV


      - name: Set up diff command
        run: |
          if [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
            echo "Initial push or force push detected. Showing full diff."
            echo "DIFF_COMMAND=git diff --stat" >> $GITHUB_ENV
          else
            echo "Diff from $BEFORE_SHA to $GITHUB_SHA:"
            echo "DIFF_COMMAND=git diff $BEFORE_SHA $GITHUB_SHA" >> $GITHUB_ENV
          fi

      - name: Show diff
        run: |
          IDS=$($DIFF_COMMAND --name-only \
            | grep -E '^devices/[0-9]+/' \
            | sed -E 's|^devices/([0-9]+)/.*|\1|' \
            | sort -u)
          echo "Unique IDs:"
          echo "$IDS"
