name: Get A Commit Test

on:
  push:
    branches: [ "main" ]

jobs:
  call-get-a-commit-api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json'
