name: Get A Commit Test

on:
  push:
    branches: [ "main" ]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 履歴を全部取得（重要）

      - name: Show commit info
        run: |
          echo "Current commit: $GITHUB_SHA"
          echo "Previous commit: $GITHUB_EVENT_BEFORE"


      - name: Show diff
        run: |
          echo "Diff from $PREV_COMMIT to HEAD:"
          git diff $GITHUB_EVENT_BEFORE $GITHUB_SHA
