name: Get A Commit Test

on:
  push:
    branches: [ "main" ]

jobs:
  call-get-a-commit-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Exec Git diff
        run: |
          IDS=$(git diff HEAD~ --name-only \
            | grep -E '^test/[^/]+/' \
            | sed -E 's|^test/([^/]+)/.*|\1|' \
            | sort -u)
          echo "Unique IDs:"
          echo "$IDS"
